/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetorabbitmq;

/**
 *
 * @author Win10
 */
public class TelaConf extends javax.swing.JFrame {

    /**
     * Creates new form TelaConf
     */
    public TelaConf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buracos = new javax.swing.JButton();
        congest = new javax.swing.JButton();
        radares = new javax.swing.JButton();
        obras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buracos.setText(" Monitor Buracos na Pista");
        buracos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buracosActionPerformed(evt);
            }
        });

        congest.setText("Monitor Congestionamento");
        congest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congestActionPerformed(evt);
            }
        });

        radares.setText("Monitor Radares");
        radares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radaresActionPerformed(evt);
            }
        });

        obras.setText("Obras na Pista");
        obras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Monitores ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buracos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(congest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(obras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(buracos)
                .addGap(18, 18, 18)
                .addComponent(congest)
                .addGap(18, 18, 18)
                .addComponent(radares)
                .addGap(18, 18, 18)
                .addComponent(obras)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buracosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buracosActionPerformed
      Sensor sensor = new Sensor();
       sensor.setTipoMsg("buracos");
       sensor.setRoutingKey("buracos");
       sensor.getNomeSensor().setText("Indice de Buracos");
       sensor.setVisible(true);
       buracos.setEnabled(false);
       
    }//GEN-LAST:event_buracosActionPerformed

    private void congestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congestActionPerformed
      Sensor sensor = new Sensor();  
      sensor.setTipoMsg("congest");
       sensor.setRoutingKey("congest");
      sensor.getNomeSensor().setText("Indice de Cogestionamento");
      sensor.setVisible(true);
      congest.setEnabled(false);
    }//GEN-LAST:event_congestActionPerformed

    private void radaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radaresActionPerformed
        Sensor sensor = new Sensor();
        sensor.setTipoMsg("radares");
         sensor.setRoutingKey("radares");
        sensor.getNomeSensor().setText("Concentração de Radares");
        sensor.setVisible(true);
        radares.setEnabled(false);
    }//GEN-LAST:event_radaresActionPerformed

    private void obrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrasActionPerformed
        Sensor sensor = new Sensor();
        sensor.setTipoMsg("obras");
         sensor.setRoutingKey("obras");
        
        sensor.getNomeSensor().setText("Obras na Pista");
        sensor.setVisible(true);
        obras.setEnabled(false);
    }//GEN-LAST:event_obrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buracos;
    private javax.swing.JButton congest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton obras;
    private javax.swing.JButton radares;
    // End of variables declaration//GEN-END:variables
}
